import { motion } from "framer-motion";
import { CalendarDays, CheckCircle2, CircleDot, MapPin, PlaneTakeoff } from "lucide-react";

type Journey = { id: string; title: string; destination: string; type: string; departureAt: string; items: { id: string; isStamped: boolean }[] };
const label = (type: string) => type.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
const airportCode = (destination: string) => destination.replace(/[^a-z]/gi, "").slice(0, 3).toUpperCase().padEnd(3, "TRP");

export default function JourneyBoardingPass({ journey, index, onOpen }: { journey: Journey; index: number; onOpen: () => void }) {
  const stamped = journey.items.filter((item) => item.isStamped).length;
  const progress = journey.items.length ? Math.round(stamped / journey.items.length * 100) : 0;
  const status = progress === 100 ? "Ready For Departure" : progress >= 75 ? "Almost Cleared" : progress > 0 ? "Packing" : "Not Started";
  const badge = progress === 100 ? "bg-emerald-600" : progress >= 75 ? "bg-[#b08d57]" : progress > 0 ? "bg-[#1e3a5f]" : "bg-[#6f4e37]";
  return <motion.button initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .06 }} whileHover={{ y: -5 }} onClick={onOpen} className="boarding-pass group relative overflow-hidden rounded-2xl bg-[#fffdf8] text-left shadow-md transition hover:shadow-2xl"><div className="p-6"><div className="flex items-start justify-between"><span className="text-[10px] font-bold uppercase tracking-[.19em] text-[#8b1e3f]">{label(journey.type)}</span><PlaneTakeoff className="h-5 w-5 text-[#b08d57]" /></div><h3 className="mt-5 font-serif text-2xl text-[#17324d]">{journey.title}</h3><div className="mt-3 flex items-center gap-2 text-sm text-[#17324d]/65"><MapPin className="h-4 w-4 text-[#8b1e3f]" />{journey.destination}</div><div className="mt-6 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#17324d]/45">Boarding code</p><p className="mt-1 font-mono text-lg font-bold tracking-[.13em] text-[#17324d]">{airportCode(journey.destination)} · GATE A12</p></div><p className="font-mono text-xs text-[#17324d]/55">PW-{journey.id.slice(-4).toUpperCase()}</p></div></div><div className="relative border-y border-dashed border-[#17324d]/20 bg-[#f6f1e7] px-6 py-4"><span className="absolute -left-3 top-1/2 h-6 w-6 -translate-y-1/2 rounded-full bg-[#f4f0e7]" /><span className="absolute -right-3 top-1/2 h-6 w-6 -translate-y-1/2 rounded-full bg-[#f4f0e7]" /><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-bold text-[#17324d]"><CalendarDays className="h-4 w-4 text-[#8b1e3f]" />{new Date(journey.departureAt).toLocaleDateString(undefined, { day: "2-digit", month: "short", year: "numeric" })}</div><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-white ${badge}`}>{progress === 100 ? <CheckCircle2 className="h-3 w-3" /> : <CircleDot className="h-3 w-3" />}{status}</span></div></div><div className="p-6"><div className="flex justify-between text-[10px] font-bold uppercase tracking-[.15em] text-[#17324d]/60"><span>Manifest clearance</span><span className="text-[#8b1e3f]">{progress}% complete</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#e5dccb]"><motion.div animate={{ width: `${progress}%` }} className="h-full rounded-full bg-[#8b1e3f]" /></div><p className="mt-3 text-xs text-[#17324d]/55">{stamped} of {journey.items.length} items stamped</p></div></motion.button>;
}
